-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
FROM (SELECT BOOK_ID, SUM(SALES) AS SALES
     FROM BOOK_SALES
     WHERE EXTRACT(YEAR FROM SALES_DATE) = '2022' AND EXTRACT(MONTH FROM SALES_DATE) = '01'
     GROUP BY BOOK_ID) BS
JOIN BOOK B ON BS.BOOK_ID = B.BOOK_ID
JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC

-- 22년 1월 책 중에서 book_id 기준으로 sales 다 더함