-- 2022년 1월의 도서 판매 데이터를 기준으로 저자 별, 카테고리 별 매출액(TOTAL_SALES = 판매량 * 판매가) 을 구하여, 저자 ID(AUTHOR_ID), 저자명(AUTHOR_NAME), 카테고리(CATEGORY), 매출액(SALES) 리스트를 출력하는 SQL문을 작성해주세요.

SELECT 
    AU.AUTHOR_ID, AU.AUTHOR_NAME, BK.CATEGORY, SUM(BK.PRICE * BS.SALES) AS TOTAL_SALES
FROM 
    BOOK_SALES BS
    JOIN BOOK BK
    ON BS.BOOK_ID = BK.BOOK_ID 
    AND EXTRACT(YEAR FROM BS.SALES_DATE) = 2022
    AND EXTRACT(MONTH FROM BS.SALES_DATE) = 1
    JOIN AUTHOR AU
    ON BK.AUTHOR_ID = AU.AUTHOR_ID
GROUP BY AU.AUTHOR_ID, AU.AUTHOR_NAME, BK.CATEGORY
ORDER BY AU.AUTHOR_ID, BK.CATEGORY DESC



-- SELECT 
--     *
-- FROM 
--     BOOK_SALES BS
--     JOIN BOOK BK
--     ON BS.BOOK_ID = BK.BOOK_ID 
--     AND EXTRACT(YEAR FROM BS.SALES_DATE) = 2022
--     AND EXTRACT(MONTH FROM BS.SALES_DATE) = 1
--     JOIN AUTHOR AU
--     ON BK.AUTHOR_ID = AU.AUTHOR_ID
-- --GROUP BY AU.AUTHOR_ID, AU.AUTHOR_NAME, BK.CATEGORY
-- ORDER BY AU.AUTHOR_ID, BK.CATEGORY DESC