-- 코드를 입력하세요
SELECT AF.ANIMAL_ID, AF.NAME
FROM (SELECT AI.ANIMAL_ID, AI.NAME
    FROM ANIMAL_INS AI JOIN ANIMAL_OUTS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
    ORDER BY AO.DATETIME - AI.DATETIME DESC
     ) AF
WHERE ROWNUM <= 2

