-- 자동차 종류가 '세단' 또는 'SUV' 인 자동차 중 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능하고 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차에 대해서 자동차 ID, 자동차 종류, 대여 금액(컬럼명: FEE) 리스트를 출력하는 SQL문을 작성해주세요.코드를 입력하세요

SELECT
    DISTINCT CC.CAR_ID, CC.CAR_TYPE, (30 * CC.DAILY_FEE) * (1-CP.DISCOUNT_RATE/100) AS FEE
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
JOIN
    CAR_RENTAL_COMPANY_CAR CC
ON
    CH.CAR_ID = CC.CAR_ID
AND
    CH.CAR_ID NOT IN (
        SELECT DISTINCT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE
            START_DATE <= TO_DATE('2022-11-30', 'yyyy-mm-dd')
        AND
            END_DATE >= TO_DATE('2022-11-01', 'yyyy-mm-dd')
    )
AND
    CC.CAR_TYPE IN ('세단', 'SUV')
JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN CP
ON
    CC.CAR_TYPE = CP.CAR_TYPE
AND 
    CP.DURATION_TYPE = '30일 이상'
AND
    (30 * CC.DAILY_FEE) * (1-CP.DISCOUNT_RATE/100) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CC.CAR_TYPE, CC.CAR_ID DESC


-- SELECT
--     *
-- FROM
--     CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
-- JOIN
--     CAR_RENTAL_COMPANY_CAR CC
-- ON
--     CH.CAR_ID = CC.CAR_ID
-- AND
--     CH.CAR_ID NOT IN (
--         SELECT DISTINCT CAR_ID
--         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
--         WHERE
--             START_DATE <= TO_DATE('2022-11-30', 'yyyy-mm-dd')
--         AND
--             END_DATE >= TO_DATE('2022-11-01', 'yyyy-mm-dd')
--     )
-- AND
--     CC.CAR_TYPE IN ('세단', 'SUV')
-- JOIN
--     CAR_RENTAL_COMPANY_DISCOUNT_PLAN CP
-- ON
--     CC.CAR_TYPE = CP.CAR_TYPE
-- AND 
--     CP.DURATION_TYPE = '30일 이상'
-- AND
--     (30 * CC.DAILY_FEE) * (1-CP.DISCOUNT_RATE/100) BETWEEN 500000 AND 1999999