SELECT
    CC.CAR_ID,
    CC.CAR_TYPE,
    (CC.DAILY_FEE * 30 * (1 - DP.DISCOUNT_RATE / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CC
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
    ON CC.CAR_TYPE = DP.CAR_TYPE
   AND DP.DURATION_TYPE = '30일 이상'
WHERE CC.CAR_TYPE IN ('세단', 'SUV')
  -- 11월 대여 불가능 차량 제외
  AND NOT EXISTS (
      SELECT 1
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
      WHERE CH.CAR_ID = CC.CAR_ID
        AND CH.START_DATE <= TO_DATE('2022-11-30','YYYY-MM-DD')
        AND CH.END_DATE   >= TO_DATE('2022-11-01','YYYY-MM-DD')
  )
  -- 대여 금액 범위 조건
  AND (CC.DAILY_FEE * 30 * (1 - DP.DISCOUNT_RATE / 100)) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CC.CAR_TYPE ASC, CC.CAR_ID DESC;