-- 코드를 입력하세요
SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES
FROM REST_INFO RI, (SELECT FOOD_TYPE, MAX(FAVORITES) as FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE) RF
WHERE RI.FOOD_TYPE = RF.FOOD_TYPE AND RI.FAVORITES = RF.FAVORITES
ORDER BY RI.FOOD_TYPE DESC