-- 음식종류별로 즐겨찾기수가 가장 많은 식당의 음식 종류, ID, 식당 이름, 즐겨찾기수를 조회하는 SQL문을 작성해주세요
SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES
FROM
    REST_INFO RI JOIN
    (
        SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAV
        FROM REST_INFO
        GROUP BY FOOD_TYPE
    ) RR ON RI.FOOD_TYPE = RR.FOOD_TYPE AND RI.FAVORITES = RR.MAX_FAV
ORDER BY RI.FOOD_TYPE DESC