SELECT U.USER_ID, U.NICKNAME, U.CITY || ' ' || U.STREET_ADDRESS1 || ' ' || U.STREET_ADDRESS2 AS 전체주소, SUBSTR(U.TLNO, 1, 3) || '-' || SUBSTR(U.TLNO, 4, 4) || '-' || SUBSTR(U.TLNO, 8, 4) AS 전화번호
FROM (
        SELECT UU.USER_ID, UU.NICKNAME, UU.CITY, UU.STREET_ADDRESS1, UU.STREET_ADDRESS2, UU.TLNO
        FROM USED_GOODS_BOARD UB JOIN USED_GOODS_USER UU ON UB.WRITER_ID = UU.USER_ID
        GROUP BY UU.USER_ID, UU.NICKNAME,  UU.CITY, UU.STREET_ADDRESS1, UU.STREET_ADDRESS2, UU.TLNO
        HAVING COUNT(UU.USER_ID) >= 3
    ) U
ORDER BY U.USER_ID DESC