-- 년, 월, 성별 별로 상품을 구매한 회원수를 집계하는 SQL문을 작성해주세요.
-- 성별 정보가 없는 경우 결과에서 제외해주세요.
-- 1 : 61   2 : 53 (51)   3 : 8
SELECT 
    EXTRACT(YEAR FROM OS.SALES_DATE) AS YEAR, 
    EXTRACT(MONTH FROM OS.SALES_DATE) MONTH,
    GENDER, 
    COUNT(DISTINCT UI.USER_ID) AS USERS
FROM 
    USER_INFO UI
JOIN
    ONLINE_SALE OS
    ON UI.USER_ID = OS.USER_ID AND UI.GENDER IS NOT NULL
GROUP BY EXTRACT(YEAR FROM OS.SALES_DATE), EXTRACT(MONTH FROM OS.SALES_DATE), GENDER
ORDER BY YEAR, MONTH, GENDER



