-- 2021년에 가입한 전체 회원들 중 상품을 구매한 회원수와 상품을 구매한 회원의 비율(=2021년에 가입한 회원 중 상품을 구매한 회원수 / 2021년에 가입한 전체 회원 수)을 년, 월 별로 출력하는 SQL문을 작성해주세요. 상품을 구매한 회원의 비율은 소수점 두번째자리에서 반올

SELECT
    EXTRACT(YEAR FROM OS.SALES_DATE) AS YEAR, 
    EXTRACT(MONTH FROM OS.SALES_DATE) AS MONTH, 
    COUNT(DISTINCT OS.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT OS.USER_ID) / TT.TOTAL_COUNT, 1) AS PURCHASED_RATIO
FROM 
    ONLINE_SALE OS
JOIN
    USER_INFO UI
ON 
    OS.USER_ID = UI.USER_ID AND EXTRACT(YEAR FROM UI.JOINED) = 2021
LEFT JOIN
    (
        SELECT COUNT(*) AS TOTAL_COUNT
        FROM USER_INFO
        WHERE EXTRACT(YEAR FROM JOINED) = 2021
    ) TT
ON 1 = 1
GROUP BY 
    EXTRACT(YEAR FROM OS.SALES_DATE), EXTRACT(MONTH FROM OS.SALES_DATE), TT.TOTAL_COUNT
ORDER BY YEAR, MONTH


-- SELECT COUNT(DISTINCT OS.USER_ID)
-- FROM ONLINE_SALE OS JOIN USER_INFO UI ON OS.USER_ID = UI.USER_ID AND EXTRACT(YEAR FROM UI.JOINED) = 2021
-- WHERE EXTRACT(YEAR FROM SALES_DATE) = 2022 AND EXTRACT(MONTH FROM SALES_DATE) = 1