-- 생산일자가 2022년 5월인 식품들의 식품 ID, 식품 이름, 총매출을 조회하는 SQL문을 작성해주세요. 이때 결과는 총매출을 기준으로 내림차순 정렬해주시고 총매출이 같다면 식품 ID를 기준으로 오름차순
-- 생산일자: PRODUCE_DATE
SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, FO.AMOUNT * FP.PRICE AS TOTAL_SALES
FROM 
    FOOD_PRODUCT FP
    JOIN
    (
        SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
        FROM FOOD_ORDER
        WHERE EXTRACT(YEAR FROM PRODUCE_DATE) = 2022
        AND EXTRACT(MONTH FROM PRODUCE_DATE) = 5
        GROUP BY PRODUCT_ID
    ) FO
    ON FP.PRODUCT_ID = FO.PRODUCT_ID 
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID

