--  자동차 종류가 '트럭'인 자동차의 대여 기록에 대해서 대여 기록 별로 대여 금액(컬럼명: FEE)을 구하여 대여 기록 ID와 대여 금액 리스트를 출력하는 SQL문을 작성해주세요.
SELECT 
    CH.HISTORY_ID,
    (CC.DAILY_FEE * (CH.END_DATE - CH.START_DATE + 1)) *
    (1 - NVL(DP.DISCOUNT_RATE, 0) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CC
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CH 
    ON CC.CAR_ID = CH.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
    ON CC.CAR_TYPE = DP.CAR_TYPE
   AND (
        (DP.DURATION_TYPE = '7일 이상'  AND (CH.END_DATE - CH.START_DATE + 1) BETWEEN 7 AND 29)
     OR (DP.DURATION_TYPE = '30일 이상' AND (CH.END_DATE - CH.START_DATE + 1) BETWEEN 30 AND 89)
     OR (DP.DURATION_TYPE = '90일 이상' AND (CH.END_DATE - CH.START_DATE + 1) >= 90)
   )
WHERE CC.CAR_TYPE = '트럭'
ORDER BY FEE DESC, CH.HISTORY_ID DESC;