-- 2022년 4월 13일 취소되지 않은 흉부외과(CS) 진료 예약 내역을 조회하는 SQL문을 작성해주세요.
SELECT AP.APNT_NO, PA.PT_NAME, PA.PT_NO, AP.MCDP_CD, DC.DR_NAME, AP.APNT_YMD
FROM 
    APPOINTMENT AP
    JOIN PATIENT PA
    ON AP.PT_NO = PA.PT_NO
    AND EXTRACT(YEAR FROM AP.APNT_YMD) = 2022 
    AND EXTRACT(MONTH FROM AP.APNT_YMD) = 4
    AND EXTRACT(DAY FROM AP.APNT_YMD) = 13
    AND AP.APNT_CNCL_YN = 'N'
    JOIN
    DOCTOR DC
    ON AP.MDDR_ID = DC.DR_ID
ORDER BY AP.APNT_YMD


    