-- 코드를 입력하세요
SELECT AP.APNT_NO, PA.PT_NAME, PA.PT_NO, AP.MCDP_CD, DC.DR_NAME, AP.APNT_YMD
FROM APPOINTMENT AP JOIN PATIENT PA ON AP.PT_NO = PA.PT_NO JOIN DOCTOR DC ON AP.MDDR_ID = DC.DR_ID
WHERE EXTRACT(YEAR FROM AP.APNT_YMD) = '2022' AND EXTRACT(MONTH FROM AP.APNT_YMD) = '04' AND EXTRACT(DAY FROM AP.APNT_YMD) = '13' AND AP.APNT_CNCL_YN = 'N'
ORDER BY AP.APNT_YMD