-- 0시부터 23시까지, 각 시간대별로 입양이 몇 건이나 발생했는지 조회하는 SQL문을 작성해주세요. 
SELECT H.HOUR AS HOUR, NVL(COUNT(AO.ANIMAL_ID), 0) AS COUNT
FROM 
    ANIMAL_OUTS AO
RIGHT JOIN (
    SELECT LEVEL - 1 AS HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24
) H
ON TO_NUMBER(TO_CHAR(AO.DATETIME, 'HH24')) = H.HOUR
GROUP BY H.HOUR
ORDER BY HOUR