-- MEMBER_PROFILE와 REST_REVIEW 테이블에서 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회하는 SQL문을 작성해주세요.
SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, TO_CHAR(RR.REVIEW_DATE, 'yyyy-mm-dd')
FROM MEMBER_PROFILE MP 
JOIN REST_REVIEW RR 
    ON MP.MEMBER_ID = RR.MEMBER_ID
JOIN 
(
    SELECT MEMBER_ID, COUNT(MEMBER_ID) 
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(MEMBER_ID) DESC
    fetch first 1 row with ties
) JJ
ON JJ.MEMBER_ID = RR.MEMBER_ID
ORDER BY RR.REVIEW_DATE, RR.REVIEW_TEXT
