-- 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회하는 SQL문을 작성해주세요. 
SELECT 
    MP.MEMBER_NAME, RR.REVIEW_TEXT, TO_CHAR(RR.REVIEW_DATE, 'yyyy-mm-dd') AS REVIEW_DATE
FROM 
    MEMBER_PROFILE MP JOIN
    (
        SELECT MEMBER_ID, DENSE_RANK() OVER (ORDER BY COUNT(MEMBER_ID) DESC) AS RANK
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
    ) LL ON MP.MEMBER_ID = LL.MEMBER_ID AND LL.RANK = 1
    JOIN REST_REVIEW RR ON RR.MEMBER_ID = MP.MEMBER_ID
ORDER BY RR.REVIEW_DATE, RR.REVIEW_TEXT

    