-- 대여 시작일을 기준으로 2022년 8월부터 2022년 10월까지 총 대여 횟수가 5회 이상인 자동차들에 대해서 해당 기간 동안의 월별 자동차 ID 별 총 대여 횟수(컬럼명: RECORDS) 리스트를 출력하는 SQL문을 작성해주세요.

SELECT EXTRACT(MONTH FROM START_DATE) AS MONTH, CAR_ID, COUNT(CAR_ID) AS RECORDS
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN 
(
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE EXTRACT(MONTH FROM START_DATE) >= 8 
            AND EXTRACT(MONTH FROM START_DATE) <= 10
        GROUP BY CAR_ID
        HAVING COUNT(CAR_ID) >= 5
    )  AND EXTRACT(MONTH FROM START_DATE) >= 8 
        AND EXTRACT(MONTH FROM START_DATE) <= 10
GROUP BY EXTRACT(MONTH FROM START_DATE), CAR_ID
ORDER BY MONTH, CAR_ID DESC
