
SELECT b.CATEGORY, SUM(bs.sales) AS TOTAL_SALES
FROM book b JOIN book_sales bs ON b.book_id = bs.book_id
WHERE EXTRACT(YEAR FROM bs.SALES_DATE) = '2022' AND EXTRACT(MONTH FROM bs.SALES_DATE) = '1'
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY