-- 코드를 입력하세요
SELECT FP.CATEGORY, FP.PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT FP JOIN  (SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
     FROM FOOD_PRODUCT
     WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
     GROUP BY CATEGORY
     ) CI ON FP.CATEGORY = CI.CATEGORY AND FP.PRICE = CI.MAX_PRICE
ORDER BY FP.PRICE DESC
